In [1]:
print("hello world")

hello world

In [2]:
import numpy as np

In [3]:
a = np.array(6) #   0  diemention
print(a,a.ndim)

6 0

In [4]:
b = np.array([1,2,3])
print(b, b.ndim)

[1 2 3] 1

In [5]:
#deactivate for deactivate script of environment
#pip install pandas
#.\env01\Scripts\activate for activate script of environment
#pip install ipykernal   for install munnal kernal

In [6]:
x = 10
y = 20

total = x + y
print(total)

30

In [7]:
import numpy as np  
import pandas as pd

In [8]:
a = np.array([1,2,3])
b = np.array(9)
c = np.array([[1,2,3,4,5,6]])

print(a, a.ndim) # 1 diementional
print(b, b.ndim)  # 0 diementional
print(c, c.ndim) # 2 diementional

[1 2 3] 1
9 0
[[1 2 3 4 5 6]] 2

In [9]:
a = np.array([[1,2,3,4,5,6],[7,8,9,10,11,12],[13,14,15,16,17,18],[19,20,21,22,23,24]])
print(a, a.ndim) # 2 diementional

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]] 2

In [10]:
#generat a prompt for making this image same as it is

In [11]:
a = np.zeros((3, 4)) # null matrix
print(a, a.ndim) # 2 diementional

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]] 2

In [12]:
b = np.ones((3, 4)) # symatic  matrix
print(b, b.ndim) # martiz 2  ndim

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]] 2

In [13]:
c = np.eye(3) # identity matrix
print(c, c.ndim) # martiz 2  ndim

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]] 2

In [14]:
d = np.random.random((3, 4)) # random matrix
print(d, d.ndim) # martiz 2  ndim

[[0.76472684 0.550176   0.95802669 0.07717665]
 [0.18215736 0.65412408 0.78624217 0.5252755 ]
 [0.51069147 0.65958517 0.0392479  0.59187996]] 2

In [15]:
e = np.arange(10) # 1D array from 10 to 30 with step of 5
print(e, e.ndim) # 1 diementional

[0 1 2 3 4 5 6 7 8 9] 1

In [16]:
f = np.linspace(0, 1, 7) # 1D array  space from 0 to 1 with 5 elements
print(f, f.ndim) # 1 diementional

[0.         0.16666667 0.33333333 0.5        0.66666667 0.83333333
 1.        ] 1

In [17]:
a = np.array([1,2,3])
b = np.array([4,5,6])
g = np.sum([a, b], axis=0) # sum of two arrays
print(g, g.ndim) # 1 diementional

[5 7 9] 1

In [18]:
# EDA of data analysis

In [19]:
#pandas

a = pd.Series([1,2,3,4,5])
print

In [20]:
a = pd.Series([1,2,3,4,5])
print(a, a.ndim) # a vector 1 ndim

0    1
1    2
2    3
3    4
4    5
dtype: int64 1

In [21]:
b = pd.DataFrame([1,2,3])
print(b, b.ndim) # a vector 2 ndim

   0
0  1
1  2
2  3 2

In [22]:
c = pd.DataFrame([[1,2,3],[4,5,6],[7,8,9]])
print(c, c.ndim) # a vector 2 ndim

   0  1  2
0  1  2  3
1  4  5  6
2  7  8  9 2

In [23]:
d = pd.DataFrame({'A': [1, 2, 3], 'B': [4, 5, 6]})
print(d, d.ndim) # a vector 2 ndim

   A  B
0  1  4
1  2  5
2  3  6 2

In [24]:
e  = pd.DataFrame({'name': ["ali","kashif","ahmad"],'age': [12, 15, 18], 'class': [12, 14, 16]})
print(e, e.ndim) # a vector 2 ndim

     name  age  class
0     ali   12     12
1  kashif   15     14
2   ahmad   18     16 2

In [25]:
#EDA  and autoML packages

In [26]:
df = pd.read_csv("D:\\Ai\\class3\\modified_data.csv")
df

,date,price,bedrooms,bathrooms,sqft_living,sqft_lot,floors,waterfront,view,condition,sqft_above,sqft_basement,yr_built,yr_renovated,street,city,statezip,price_per_sqft
0,2014-05-02,313000.00,3.0,1.50,1340,7912,1.5,0,0,3,1340,0,1955,2005,18810 Densmore Ave N,Shoreline,WA 98133,233.58
1,2014-05-02,2384000.00,5.0,2.50,3650,9050,2.0,0,4,5,3370,280,1921,0,709 W Blaine St,Seattle,WA 98119,653.15
2,2014-05-02,342000.00,3.0,2.00,1930,11947,1.0,0,0,4,1930,0,1966,0,26206-26214 143rd Ave SE,Kent,WA 98042,177.20
3,2014-05-02,420000.00,3.0,2.25,2000,8030,1.0,0,0,4,1000,1000,1963,0,857 170th Pl NE,Bellevue,WA 98008,210.00
4,2014-05-02,550000.00,4.0,2.50,1940,10500,1.0,0,0,4,1140,800,1976,1992,9105 170th Ave NE,Redmond,WA 98052,283.51
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4595,2014-07-09,308166.67,3.0,1.75,1510,6360,1.0,0,0,4,1510,0,1954,1979,501 N 143rd St,Seattle,WA 98133,204.08
4596,2014-07-09,534333.33,3.0,2.50,1460,7573,2.0,0,0,3,1460,0,1983,2009,14855 SE 10th Pl,Bellevue,WA 98007,365.98
4597,2014-07-09,416904.17,3.0,2.50,3010,7014,2.0,0,0,3,3010,0,2009,0,759 Ilwaco Pl NE,Renton,WA 98059,138.51
4598,2014-07-10,203400.00,4.0,2.00,2090,6630,1.0,0,0,3,1070,1020,1974,0,5148 S Creston St,Seattle,WA 98178,97.32
4599,2014-07-10,220600.00,3.0,2.50,1490,8102,2.0,0,0,4,1490,0,1990,0,18717 SE 258th St,Covington,WA 98042,148.05

In [ ]:
print(df.isnull().sum()) #check for missing value
#model art and Explorations data analysis

date              0
price             0
bedrooms          0
bathrooms         0
sqft_living       0
sqft_lot          0
floors            0
waterfront        0
view              0
condition         0
sqft_above        0
sqft_basement     0
yr_built          0
yr_renovated      0
street            0
city              0
statezip          0
price_per_sqft    0
dtype: int64

In [28]:
print(df.info())

<class 'pandas.DataFrame'>
RangeIndex: 4600 entries, 0 to 4599
Data columns (total 18 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   date            4600 non-null   str
 1   price           4600 non-null   float64
 2   bedrooms        4600 non-null   float64
 3   bathrooms       4600 non-null   float64
 4   sqft_living     4600 non-null   int64
 5   sqft_lot        4600 non-null   int64
 6   floors          4600 non-null   float64
 7   waterfront      4600 non-null   int64
 8   view            4600 non-null   int64
 9   condition       4600 non-null   int64
 10  sqft_above      4600 non-null   int64
 11  sqft_basement   4600 non-null   int64
 12  yr_built        4600 non-null   int64
 13  yr_renovated    4600 non-null   int64
 14  street          4600 non-null   str
 15  city            4600 non-null   str
 16  statezip        4600 non-null   str
 17  price_per_sqft  4600 non-null   float64
dtypes: float64(5), int64(9), str(4)
memory usage: 647.0 KB
None

In [ ]:
#number inthe form of martix for images  in ai
#text in the form of vector in ai

In [ ]:
#scalar is with out brackets
#vector in form of text 
#difference betweeb vector and matrixeson ai

In [33]:
df = df.dropna() # drop value who is missing value

In [34]:
print(df)

            date       price  bedrooms  bathrooms  sqft_living  sqft_lot  \
0     2014-05-02   313000.00       3.0       1.50         1340      7912
1     2014-05-02  2384000.00       5.0       2.50         3650      9050
2     2014-05-02   342000.00       3.0       2.00         1930     11947
3     2014-05-02   420000.00       3.0       2.25         2000      8030
4     2014-05-02   550000.00       4.0       2.50         1940     10500
...          ...         ...       ...        ...          ...       ...
4595  2014-07-09   308166.67       3.0       1.75         1510      6360
4596  2014-07-09   534333.33       3.0       2.50         1460      7573
4597  2014-07-09   416904.17       3.0       2.50         3010      7014
4598  2014-07-10   203400.00       4.0       2.00         2090      6630
4599  2014-07-10   220600.00       3.0       2.50         1490      8102

      floors  waterfront  view  condition  sqft_above  sqft_basement  \
0        1.5           0     0          3        1340              0
1        2.0           0     4          5        3370            280
2        1.0           0     0          4        1930              0
3        1.0           0     0          4        1000           1000
4        1.0           0     0          4        1140            800
...      ...         ...   ...        ...         ...            ...
4595     1.0           0     0          4        1510              0
4596     2.0           0     0          3        1460              0
4597     2.0           0     0          3        3010              0
4598     1.0           0     0          3        1070           1020
4599     2.0           0     0          4        1490              0

      yr_built  yr_renovated                    street       city  statezip  \
0         1955          2005      18810 Densmore Ave N  Shoreline  WA 98133
1         1921             0           709 W Blaine St    Seattle  WA 98119
2         1966             0  26206-26214 143rd Ave SE       Kent  WA 98042
3         1963             0           857 170th Pl NE   Bellevue  WA 98008
4         1976          1992         9105 170th Ave NE    Redmond  WA 98052
...        ...           ...                       ...        ...       ...
4595      1954          1979            501 N 143rd St    Seattle  WA 98133
4596      1983          2009          14855 SE 10th Pl   Bellevue  WA 98007
4597      2009             0          759 Ilwaco Pl NE     Renton  WA 98059
4598      1974             0         5148 S Creston St    Seattle  WA 98178
4599      1990             0         18717 SE 258th St  Covington  WA 98042

      price_per_sqft
0             233.58
1             653.15
2             177.20
3             210.00
4             283.51
...              ...
4595          204.08
4596          365.98
4597          138.51
4598           97.32
4599          148.05

[4600 rows x 18 columns]

In [35]:
print(df.iloc[1]) #print first row

date                   2014-05-02
price                   2384000.0
bedrooms                      5.0
bathrooms                     2.5
sqft_living                  3650
sqft_lot                     9050
floors                        2.0
waterfront                      0
view                            4
condition                       5
sqft_above                   3370
sqft_basement                 280
yr_built                     1921
yr_renovated                    0
street            709 W Blaine St
city                      Seattle
statezip                 WA 98119
price_per_sqft             653.15
Name: 1, dtype: object

In [ ]:
print(df.iloc[1 : 2]) #mulriple value

         date      price  bedrooms  bathrooms  sqft_living  sqft_lot  floors  \
1  2014-05-02  2384000.0       5.0        2.5         3650      9050     2.0

   waterfront  view  condition  sqft_above  sqft_basement  yr_built  \
1           0     4          5        3370            280      1921

   yr_renovated           street     city  statezip  price_per_sqft
1             0  709 W Blaine St  Seattle  WA 98119          653.15

In [37]:
print(df.loc[1])

date                   2014-05-02
price                   2384000.0
bedrooms                      5.0
bathrooms                     2.5
sqft_living                  3650
sqft_lot                     9050
floors                        2.0
waterfront                      0
view                            4
condition                       5
sqft_above                   3370
sqft_basement                 280
yr_built                     1921
yr_renovated                    0
street            709 W Blaine St
city                      Seattle
statezip                 WA 98119
price_per_sqft             653.15
Name: 1, dtype: object

In [ ]:
print(df.iloc[-1]) #last value print

date                     2014-07-10
price                      220600.0
bedrooms                        3.0
bathrooms                       2.5
sqft_living                    1490
sqft_lot                       8102
floors                          2.0
waterfront                        0
view                              0
condition                         4
sqft_above                     1490
sqft_basement                     0
yr_built                       1990
yr_renovated                      0
street            18717 SE 258th St
city                      Covington
statezip                   WA 98042
price_per_sqft               148.05
Name: 4599, dtype: object

In [41]:
df.head()

,date,price,bedrooms,bathrooms,sqft_living,sqft_lot,floors,waterfront,view,condition,sqft_above,sqft_basement,yr_built,yr_renovated,street,city,statezip,price_per_sqft
0,2014-05-02,313000.0,3.0,1.50,1340,7912,1.5,0,0,3,1340,0,1955,2005,18810 Densmore Ave N,Shoreline,WA 98133,233.58
1,2014-05-02,2384000.0,5.0,2.50,3650,9050,2.0,0,4,5,3370,280,1921,0,709 W Blaine St,Seattle,WA 98119,653.15
2,2014-05-02,342000.0,3.0,2.00,1930,11947,1.0,0,0,4,1930,0,1966,0,26206-26214 143rd Ave SE,Kent,WA 98042,177.20
3,2014-05-02,420000.0,3.0,2.25,2000,8030,1.0,0,0,4,1000,1000,1963,0,857 170th Pl NE,Bellevue,WA 98008,210.00
4,2014-05-02,550000.0,4.0,2.50,1940,10500,1.0,0,0,4,1140,800,1976,1992,9105 170th Ave NE,Redmond,WA 98052,283.51

In [47]:
df.tail()

,date,price,bedrooms,bathrooms,sqft_living,sqft_lot,floors,waterfront,view,condition,sqft_above,sqft_basement,yr_built,yr_renovated,street,city,statezip,price_per_sqft
4595,2014-07-09,308166.67,3.0,1.75,1510,6360,1.0,0,0,4,1510,0,1954,1979,501 N 143rd St,Seattle,WA 98133,204.08
4596,2014-07-09,534333.33,3.0,2.50,1460,7573,2.0,0,0,3,1460,0,1983,2009,14855 SE 10th Pl,Bellevue,WA 98007,365.98
4597,2014-07-09,416904.17,3.0,2.50,3010,7014,2.0,0,0,3,3010,0,2009,0,759 Ilwaco Pl NE,Renton,WA 98059,138.51
4598,2014-07-10,203400.00,4.0,2.00,2090,6630,1.0,0,0,3,1070,1020,1974,0,5148 S Creston St,Seattle,WA 98178,97.32
4599,2014-07-10,220600.00,3.0,2.50,1490,8102,2.0,0,0,4,1490,0,1990,0,18717 SE 258th St,Covington,WA 98042,148.05

In [48]:
df = df.drop(2)
df.head()

,date,price,bedrooms,bathrooms,sqft_living,sqft_lot,floors,waterfront,view,condition,sqft_above,sqft_basement,yr_built,yr_renovated,street,city,statezip,price_per_sqft
0,2014-05-02,313000.0,3.0,1.50,1340,7912,1.5,0,0,3,1340,0,1955,2005,18810 Densmore Ave N,Shoreline,WA 98133,233.58
1,2014-05-02,2384000.0,5.0,2.50,3650,9050,2.0,0,4,5,3370,280,1921,0,709 W Blaine St,Seattle,WA 98119,653.15
3,2014-05-02,420000.0,3.0,2.25,2000,8030,1.0,0,0,4,1000,1000,1963,0,857 170th Pl NE,Bellevue,WA 98008,210.00
4,2014-05-02,550000.0,4.0,2.50,1940,10500,1.0,0,0,4,1140,800,1976,1992,9105 170th Ave NE,Redmond,WA 98052,283.51
5,2014-05-02,490000.0,2.0,1.00,880,6380,1.0,0,0,3,880,0,1938,1994,522 NE 88th St,Seattle,WA 98115,556.82

In [52]:
df = df.fillna(df["sqft_basement"].mean()) # fill misssing value by mean
print(df)

            date       price  bedrooms  bathrooms  sqft_living  sqft_lot  \
0     2014-05-02   313000.00       3.0       1.50         1340      7912
1     2014-05-02  2384000.00       5.0       2.50         3650      9050
3     2014-05-02   420000.00       3.0       2.25         2000      8030
4     2014-05-02   550000.00       4.0       2.50         1940     10500
5     2014-05-02   490000.00       2.0       1.00          880      6380
...          ...         ...       ...        ...          ...       ...
4595  2014-07-09   308166.67       3.0       1.75         1510      6360
4596  2014-07-09   534333.33       3.0       2.50         1460      7573
4597  2014-07-09   416904.17       3.0       2.50         3010      7014
4598  2014-07-10   203400.00       4.0       2.00         2090      6630
4599  2014-07-10   220600.00       3.0       2.50         1490      8102

      floors  waterfront  view  condition  sqft_above  sqft_basement  \
0        1.5           0     0          3        1340              0
1        2.0           0     4          5        3370            280
3        1.0           0     0          4        1000           1000
4        1.0           0     0          4        1140            800
5        1.0           0     0          3         880              0
...      ...         ...   ...        ...         ...            ...
4595     1.0           0     0          4        1510              0
4596     2.0           0     0          3        1460              0
4597     2.0           0     0          3        3010              0
4598     1.0           0     0          3        1070           1020
4599     2.0           0     0          4        1490              0

      yr_built  yr_renovated                street       city  statezip  \
0         1955          2005  18810 Densmore Ave N  Shoreline  WA 98133
1         1921             0       709 W Blaine St    Seattle  WA 98119
3         1963             0       857 170th Pl NE   Bellevue  WA 98008
4         1976          1992     9105 170th Ave NE    Redmond  WA 98052
5         1938          1994        522 NE 88th St    Seattle  WA 98115
...        ...           ...                   ...        ...       ...
4595      1954          1979        501 N 143rd St    Seattle  WA 98133
4596      1983          2009      14855 SE 10th Pl   Bellevue  WA 98007
4597      2009             0      759 Ilwaco Pl NE     Renton  WA 98059
4598      1974             0     5148 S Creston St    Seattle  WA 98178
4599      1990             0     18717 SE 258th St  Covington  WA 98042

      price_per_sqft
0             233.58
1             653.15
3             210.00
4             283.51
5             556.82
...              ...
4595          204.08
4596          365.98
4597          138.51
4598           97.32
4599          148.05

[4599 rows x 18 columns]